package com.phonepe.accounting.ledger.sideline.foxtrot;

public enum EventTypes {
  SIDELINE_TRANSACTION_EVENT_PARSING_ERROR,
  NO_ACTION_LEDGER_SIDELINE_EVENT_RECEIVED,
  NO_ACTION_LEDGER_SIDELINE_EVENT_SAVED,
  NO_ACTION_LEDGER_SIDELINE_EVENT_DELETE,
  NO_ACTION_LEDGER_SIDELINE_EVENT_ALREADY_EXIST,
  NO_ACTION_LEDGER_SIDELINE_EVENT_NOT_EXIST;



}
